run_name: 8-load-fsdp-sharded-static-125m-err
image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04
gpu_num: 16
gpu_type: a100_40gb
cluster: r7z2

integrations:
  - integration_type: wandb
    project: release-v-0-13-2-chkpt-tests
    entity: mosaic-ml
  - integration_type: git_repo
    git_repo: mosaicml/examples
    git_branch: hero-3-3
    pip_install: .[llm]
  - integration_type: git_repo
    git_repo: mosaicml/composer
    git_branch: release/v0.13.2
    pip_install: '.[all]'

command: |
  cd examples/examples/llm
  composer main.py /mnt/config/parameters.yaml save_folder=s3://mosaicml-internal-checkpoints-test/evan-test/checkpoints/gpt_125m/sharded/{run_name}
  composer main.py /mnt/config/parameters.yaml max_duration=4ba load_path=s3://mosaicml-internal-checkpoints-test/evan-test/checkpoints/gpt_125m/sharded/8-load-fsdp-sharded-static-125m-err/ep0-ba2-rank0.pt

parameters:
  data_local: ./my-copy-c4
  data_remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k
  tokenizer_name: gpt2
  max_seq_len: 2048
  global_seed: 17

  # Run Name
  run_name: 8-load-fsdp-sharded-static-125m-err

  # Model
  model:
    name: mosaic_gpt
    init_device: meta
    tokenizer_name: ${tokenizer_name}
    d_model: 768
    n_heads: 12
    n_layers: 12
    mlp_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 50257
    init_std: 0.02
    attn_pdrop: 0.0
    resid_pdrop: 0.0
    emb_pdrop: 0.0
    attn_impl: flash

  # Tokenizer
  tokenizer:
    type: hftokenizer
    args:
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}

  # Dataloaders
  train_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${data_remote}
      split: train
      shuffle: true
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: true
    num_workers: 8

  eval_loader:
    name: text
    dataset:
      local: ${data_local}
      remote: ${data_remote}
      split: val
      shuffle: false
      tokenizer_name: ${tokenizer_name}
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: false
    num_workers: 8

  # Optimization
  scheduler:
    name: cosine_with_warmup
    t_warmup: 100ba
    alpha_f: 0.1

  optimizer:
    name: decoupled_adamw
    lr: 6.0e-4
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 0.0

  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  eval_first: false
  eval_interval: 4ba
  eval_subset_num_batches: -1
  global_train_batch_size: 16

  # System
  seed: ${global_seed}
  device_eval_batch_size: 16
  device_train_microbatch_size: 1
  # device_train_microbatch_size: auto
  precision: amp_bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: DEFAULT
    activation_checkpointing: false
    activation_cpu_offload: false
    verbose: false
    state_dict_type: 'local'

  # Logging
  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    # health_checker: {}
    optimizer_monitor: {}
    # runtime_estimator: {}

  # ICL Eval
  icl_tasks:
  -
    label: lambada
    dataset_uri: s3://mosaicml-internal-dataset-lambda/lambada/lambada_standard.jsonl
    num_fewshot:
    - 0
    batch_size: 16
    icl_task_type: language_modeling
    metric_names:
    - InContextLearningLMAccuracy
    prompt_string: '' # this goes at the beginning of each input
    example_delimiter: '\n' # this goes between fewshot examples
    continuation_delimiter: '' # this separates contexts from continuations

  loggers:
    wandb: {}

  python_log_level: debug
  max_duration: 2ba # ~ 2.5B tokens
  # Checkpoint to local filesystem or remote object store
  # save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
  # save_folder: ./{run_name}/checkpoints
  # save_folder: s3://mosaicml-internal-checkpoints-test/evan-test/checkpoints/gpt_125m/sharded/{run_name}
  save_overwrite: false

  # Load from local filesystem or remote object store
  # load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
  #load_path: s3://mosaicml-internal-checkpoints-test/evan-test/checkpoints/gpt_13b/fsdp-unsharded/pr-2071-load-fsdp-full-no-fstring/ep0-ba2-rank0.pt
